### PR TITLE
feature: switch to a multi-stage build

### LINKED ISSUE #99: Switch to the multi-stage build pattern
Looking at the Dockerfile and the image's history (see below), it seems we can save quite a bit of space by switching to the [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) pattern.

It should allow us to avoid having a 250MB+ intermediate layer in the image:

```
$ docker history jakzal/phpqa:alpine 
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
76b1555a30f9        19 hours ago        /bin/sh -c #(nop)  CMD ["/bin/sh" "-c" "php …   0B                  
<missing>           19 hours ago        /bin/sh -c apk add --no-cache --virtual .too…   252MB               
<missing>           19 hours ago        /bin/sh -c #(nop) COPY file:60fad6cf4445b0d0…   1.88MB              
<missing>           19 hours ago        /bin/sh -c #(nop) COPY file:287ae7377cdad1b1…   23.6kB              
<missing>           19 hours ago        /bin/sh -c #(nop) COPY file:850923d8354d1f73…   18.7kB              
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV TOOLS_JSON=/tools/too…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV PATH=/usr/local/sbin:…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV TOOL_DEPS=git graphvi…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV LIB_DEPS=zlib-dev        0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV BUILD_DEPS=autoconf f…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV COMPOSER_HOME=/tools/…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  ENV COMPOSER_ALLOW_SUPERU…   0B                  
<missing>           19 hours ago        /bin/sh -c #(nop)  LABEL maintainer=Jakub Za…   0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  CMD ["php" "-a"]             0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  ENTRYPOINT ["docker-php-e…   0B                  
<missing>           2 weeks ago         /bin/sh -c docker-php-ext-enable sodium         168kB               
<missing>           2 weeks ago         /bin/sh -c #(nop) COPY multi:2cdcedabcf5a3b9…   6.42kB              
<missing>           2 weeks ago         /bin/sh -c set -xe  && apk add --no-cache --…   58.1MB              
<missing>           2 weeks ago         /bin/sh -c #(nop) COPY file:207c686e3fed4f71…   587B                
<missing>           2 weeks ago         /bin/sh -c set -xe;   apk add --no-cache --v…   12.2MB              
<missing>           2 weeks ago         /bin/sh -c #(nop)  ENV PHP_SHA256=da1a705c0b…   0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  ENV PHP_URL=https://secur…   0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  ENV PHP_VERSION=7.2.11       0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV GPG_KEYS=1729F83938DA…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_LDFLAGS=-Wl,-O1 -…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_CPPFLAGS=-fstack-…   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_CFLAGS=-fstack-pr…   0B                  
<missing>           6 weeks ago         /bin/sh -c mkdir -p $PHP_INI_DIR/conf.d         0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHP_INI_DIR=/usr/loca…   0B                  
<missing>           6 weeks ago         /bin/sh -c set -x  && addgroup -g 82 -S www-…   4.85kB              
<missing>           6 weeks ago         /bin/sh -c apk add --no-cache --virtual .per…   2.69MB              
<missing>           6 weeks ago         /bin/sh -c #(nop)  ENV PHPIZE_DEPS=autoconf …   0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:25c10b1d1b41d46a1…   4.41MB   
```

### PR DESCRIPTION
**Pull request by dkarlovi**
Closes #99.

### CODE REVIEW

**Comment by dkarlovi** [comment]
@jakzal we can probably use some sort of templating (like the one built into Go) to keep both Debian and Alpine in the same Dockerfile since they're almost identical, they differ only in a few package names and the package install command (`apt` vs `apk`).

**Comment by dkarlovi** [comment]
Not sure I understand the current failures. :thinking:

**Comment by dkarlovi** [comment]
NVM it should work now, it was a PEBKAC. :see_no_evil:

**Comment by dkarlovi** [comment]
It works now, but it seems glitchy, I've also noticed you have the same failures in master, do you have any ideas why it happens? The build passes successfully and all the tools run too.

**Comment by jakzal** [comment]
I think the github token might have been revoked at some point and we sometimes get issues downloading all the packages :)

**Comment by jakzal** [comment]
> we can probably use some sort of templating (like the one built into Go) to keep both Debian and Alpine in the same Dockerfile

Not sure if this is necessary. My fear is it would be harder to understand, especially when both images diverge more over time.

**Comment by dkarlovi** [comment]
> I think the github token might have been revoked at some point and we sometimes get issues downloading all the packages :)

Not sure about that, if you check the build, it completed the installation process and everything went into the final image (judging by the fact the test run passes).

The problem seems to be checking for PHP in the image, but only sometimes. I have no idea why it would do that (?).

**Comment by dkarlovi** [comment]
I just realized there are actually two separate issues, it's complaining about missing `phpda` on < 7.3, weird. Will look at that tomorrow.

But the PHP issue is weird, like it cannot find the expected version of PHP in the image.

**Comment by dkarlovi** [comment]
I'm dumb, the base image version doesn't get parsed properly. :angel:

**Comment by dkarlovi** [comment]
@jakzal ready for review.

**Comment by dkarlovi** [comment]
@jakzal do you still want this or shall I close here?

**Comment by jakzal** [comment]
Do you remember if there were any differences in the image size (before/after transition)?

**Comment by dkarlovi** [comment]
I think it was a bit smaller, yes, don't have the exact numbers.

The major difference is we can now take advantage of build layers in the build stage, since the layers are not included in the final image. So we could break apart the build steps into discrete steps and changing step 15 wouldn't bust cache for all previous steps, which now happens since everything in a single step.

**Comment by dkarlovi** [comment]
Obsoleted by #302.

**Pull request closed without merging**
