### PR TITLE
feature: rudimentary environment requirements support

### PR DESCRIPTION
**Pull request by dkarlovi**
Allow to skip testing tools which explicitly require a non-satisfied environment.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Required for #88 build to pass.

**Comment by dkarlovi** [comment]
In the future we could

- remove all the tools from the output if on non-supported version
- add a stub which does basically:

```
echo Unsupported PHP version, requires $VERSION;
exit 1;
```

at path of each tool unsupported by current env.

**Comment by dkarlovi** [comment]
Closing as it's being done in Toolbox.

**Comment by jakzal** [comment]
@dkarlovi what I was planning to do in toolbox is to introduce tags, so we could label each tool. Excluding tools could then be done with filters i.e. `--exclude-tags php7.2,php7.3`

**Comment by dkarlovi** [comment]
@jakzal sounds good. :+1: Do you need any help on Toolbox or getting it merged here, I might have a bit of time during next month.

**Comment by jakzal** [comment]
@dkarlovi help is appreciated. I just need to write up what needs to be done first. Will ping you when I have a list ;)

**Pull request closed without merging**
