### PR TITLE
doc/cookbook with two first recipes 

### PR DESCRIPTION
**Pull request by dgoosens**
hi @jakzal 

as discussed in #344 here are the first recipes  for the PHPQA Cookbook...  

it includes:

- cookbook for AMPQ extension
- cookbook for Xdebug
- index of the cookbook
- reference in the base README to the cookbook

dGo

### CODE REVIEW

**Comment by dgoosens** [comment]
typos corrected

dGo

**Comment by jakzal** [comment]
What do you think of adding contribution credits at the top of each cookboo?

```
Contributed by [dgoosens](https://github.com/dgoosens).
```

**Comment by dgoosens** [comment]
> What do you think of adding contribution credits at the top of each cookbook?

that's a very good idea...  
just updated

**Comment by jakzal** [comment]
Great work @dgoosens 🍺

**Pull request merged**
