### PR TITLE
feat: PHP 8.3

### PR DESCRIPTION
**Pull request by dkarlovi**

### CODE REVIEW

**Comment by jakzal** [comment]
Thanks! 

I guess, as always, [toolbox](https://github.com/jakzal/toolbox/) will delay this.

**Comment by dkarlovi** [comment]
Also the Docker images are still not here, but let's see what breaks. :smile:

**Comment by dkarlovi** [comment]
I guess we need to bump toolbox version here or will it happen automagically?

**Comment by dkarlovi** [comment]
Seems `buster` is out, only `bookworm` and `bullseye` is available for 8.3.

**Comment by jakzal** [comment]
Yeah, let's go with `bookworm` 👍

**Comment by jakzal** [comment]
Thank you @dkarlovi 🍻

**Comment by dkarlovi** [comment]
@jakzal would you mind awfully tagging a new release? :angel:

**Comment by jakzal** [comment]
@dkarlovi I just tagged v1.93.0 https://github.com/jakzal/phpqa/releases/tag/v1.93.0 👍

**Pull request merged**
