### PR TITLE
Provide 7.4 images

### PR DESCRIPTION
**Pull request by jakzal**

### CODE REVIEW

**Comment by dkarlovi** [comment]
Could we move forward here, PHP 7.4 is right around the corner. :)

**Comment by jakzal** [comment]
I don't expect a lot of tools will support PHP 7.4 early on, so we might need to disable a lot of them.

Also, we might need to get https://github.com/jakzal/toolbox/pull/86 in first. Even though technically the legacy version of box allows any post 5.3 PHP version, it might not work.

**Comment by jakzal** [comment]
I rebased this PR and kicked off a new build.

It went much further than the last time. It currently fails on symfony/phpunit-bridge installation:

```
Using version ^4.3 for symfony/phpunit-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/phpunit-bridge (v4.3.5): Downloading (connecting...)Downloading (100%)
Writing lock file
Generating autoload files
Installing phpunit/phpunit (7.4.5)
Plugins have been disabled.
  - Installing phpunit/phpunit (7.4.5): Downloading (100%)
Created project in phpunit-7.4
composer.json has been updated
Loading composer repositories with package information

                                                       
  [ErrorException]                                     
  Trying to access array offset on value of type null                                                         
```

ping @ro0NL :)

**Comment by dkarlovi** [comment]
It makes sense to me to disable a few incompatible tools, this will need to be done anyway if 7.4 comes out and they're not updated.

I can continue with this branch if you lack the time.

**Comment by jakzal** [comment]
Go ahead if you have time. I might not be able to do it before next weekend.

**Comment by thunderer** [comment]
@dkarlovi @jakzal I built the `7.4-rc` image without any problem, it seems that vendors have caught up. Could you please upgrade Deptrac to `v0.6` and rerun the pipeline?

**Comment by jakzal** [comment]
@thunderer deptrac is already on v0.6 

I just restarted the build.

**Comment by thunderer** [comment]
@jakzal I just pulled the latest image and it's still on `v0.5`. Anything else I can do? Did you push the latest version into Docker registry?

```
$ docker pull jakzal/phpqa
...
Status: Downloaded newer image for jakzal/phpqa:latest
docker.io/jakzal/phpqa:latest
$ phpqa deptrac --version 
deptrac 0.5.0
```

**Comment by dkarlovi** [comment]
Build passed, the only thing which doesn't work is the version detection, I'm guessing because the version PHP reports doesn't contain the RC information, I've discovered this while working on #172.

**Comment by jakzal** [comment]
pdepend doesn't work with PHP 7.4 at the moment

**Comment by jakzal** [comment]
I can't really build toolbox on PHP 7.4: https://travis-ci.com/jakzal/toolbox/jobs/257802338#L297

We still use the outdated and unmaintained version of box (see https://github.com/jakzal/toolbox/pull/86).

**Comment by jakzal** [comment]
@thunderer i was mistaken. Made a new release now to include the latest deptrac: https://github.com/jakzal/phpqa/releases/tag/v1.24.4

**Pull request merged**
