### PR TITLE
feat: enable PHP 8.1

### PR DESCRIPTION
**Pull request by dkarlovi**
Create the 8.1 image set.

### CODE REVIEW

**Comment by jakzal** [comment]
Thanks for working on this. 

We first need to get toolbox to support PHP 8.1: https://github.com/jakzal/toolbox/pull/397

**Comment by dkarlovi** [comment]
@jakzal I know, I wanted to set it up here so we have something to rebase. :)

**Comment by jakzal** [comment]
@dkarlovi just remembered you started it. Do you have time to rebase? :)

**Comment by dkarlovi** [comment]
Go ahead if you already have it done, no hrm done. 👌

**Comment by jakzal** [comment]
Thanks! I forgot about nightly builds by the way. Your PR helped me :)

**Comment by jakzal** [comment]
@dkarlovi I rebased your PR after all. Thought it's good to give credit when credit is due! ;)

**Comment by dkarlovi** [comment]
That's nice of you, but don't make it create work for you, whichever way we get to PHP 8.1 images is awesome for me! :beers:

**Comment by jakzal** [comment]
Ugh... looks like PHP 8.1.0 works while PHP 8.1.1 doesn't.

**Comment by dkarlovi** [comment]
@jakzal it's always like that. :laughing:

**Pull request closed without merging**
