### PR TITLE
feat: add current UID as `phpqa` user

### LINKED ISSUE #354: If running as non-root, ensure there exists a user with the current UID in the user list
If you're passing your SSH keys mounted to the container, they need to have the correct permissions for SSH to want to use them.

```
Bad owner or permissions on /root/.ssh/config
```

This goes further: if you pass the correct keys with the correct permissions, SSH still checks the UID matches a known user, it cannot just be UIDs:

```
No user exists for uid 2000
fatal: Could not read from remote repository.
```

We could create a user from the entrypoint script if no such user currently exists, this could be as easy as:

```bash
# in the entrypoint
useradd -d /home/user -u `id -u` user || true
```

This would create a user called `user` with the home set to `/home/user` or ignore, if the user already exists (you're running as `root`). It also means you get to mount stuff into it (say, `/home/user/.ssh:ro`) and it all just works.

### PR DESCRIPTION
**Pull request by dkarlovi**
Closes #354.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Note, didn't test this fully yet locally, I keep running into GH rate limits when rebuilding the images, not sure how to pass my Composer GH credentials to the build process.

**Comment by dkarlovi** [comment]
OK, in theory it should work since the build passes, I'll mark as ready once I'm able to build and test locally.

In short, this should work:
```
$ docker run --user <which ever ID not already present in the image, for example 2000> --rm -ti jakzal/phpqa:alpine whoami
phpqa
```

**Comment by jakzal** [comment]
What if we just created the user in Dockerfile, but altered their id in the entrypoint with usermod (if/when needed)?

**Comment by jakzal** [comment]
Not needed anymore?

**Comment by dkarlovi** [comment]
@jakzal we've switched to Private Packagist so I'll not be working on this any time soon, silly to keep it open.

**Pull request closed without merging**
