### PR TITLE
Add builds for PHP 8.1 

### PR DESCRIPTION
**Pull request by jakzal**
fixes #334 #322

### CODE REVIEW

**Comment by jakzal** [comment]
Likely to be fixed by https://github.com/box-project/box/pull/578

**Comment by odolbeau** [comment]
@jakzal it looks like box-project/box#578 have been merged, could you relaunch tests & eventually merge this PR please?

**Comment by jakzal** [comment]
box-project/box#578 isn't sufficient alone. See https://github.com/box-project/box/pull/578#issuecomment-998695716

Also, the latest phar is missing: https://github.com/box-project/box/issues/586

**Comment by goetas** [comment]
it would be great to see this soon :pray:

**Comment by jakzal** [comment]
I guess the box project would appreciate some help to get it working on PHP 8.1.

**Comment by jakzal** [comment]
https://github.com/jakzal/phpqa/releases/tag/v1.66.0

**Pull request merged**
