### PR TITLE
Preparing to add phive requires GPG support at runtime.

### PR DESCRIPTION
**Pull request by mihai-stancu**
I'm adding [`phive`](https://phar.io) to `phpqa` via jakzal/toolbox#369.

In support of that `phpqa` needs to have GPG available at runtime.

### CODE REVIEW

**Comment by mihai-stancu** [comment]
Hey @jakzal is this a good time to shamelessly plug #285 ?

Adding `php-gd` and `php-mysql` support by default would make `phpqa` an image you can use as is in CI/CD pipelines to run functional/integration tests.

**Comment by mihai-stancu** [comment]
@jakzal some phpstan constraint issue has surfaced.

**Comment by jakzal** [comment]
Yes, they made the change within 20mins of toolbox release 😂 

Anyway, I made a new release that fixed the problem.

**Comment by mihai-stancu** [comment]
The this should only require a rerun of the build-checks and it should be done & can be merged even without updating the toolbox, right?

**Comment by jakzal** [comment]
You'll need to rebase to get the latest toolbox.

**Comment by mihai-stancu** [comment]
Ping.

**Review by jakzal — APPROVED** [review]

**Comment by jakzal** [comment]
Thank you @mihai-stancu

**Pull request merged**
