### PR TITLE
Add a mention to docker run --init option in the README

### PR DESCRIPTION
**Pull request by pylebecq**
Hello,

Thank you for creating this docker image, it's really convenient to have all these tools in a single image.

Today I was using it to run a bunch of tools on my code and at some point one of them took too much time to run. So I tried to cancel it, using a Control-C as usual but of course, it's not working the same way when running in a container.

>  docker run -it --rm -v $PWD:/project -v $PWD/tmp-phpqa:/tmp -w /project jakzal/phpqa deprecation-detector                                                                                               
> Checking your application for deprecations - this could take a while ...                                                                                                               
>                                                                                                                                                                                        
> Loading RuleSet...                                                                                                                                                                     
>                                                                                                                                                                                        
> ^C^C^C^C^C^C^CRuleSet loaded.                                                                                                                                                          
>                                                                                                                                                                                        
> Parsing files & Searching for deprecations...                                                                                                                                          
>                                                                                                                                                                                        
> Finished searching for deprecations.                                                                                                                                                   
>                                                                                                                                                                                        
> Rendering output...

Most of the time I use [dumb-init](https://github.com/Yelp/dumb-init) to handle these kind of issues so I added it and I thought maybe it will please everyone to benefit from it.
With these changes you can now Control-C any tools you run using this image.

I thought that maybe other users might find this useful.

### CODE REVIEW

**Comment by pylebecq** [comment]
There are some issues to fix, I will update my branch very soon

**Comment by jakzal** [comment]
Thank you so much for your contribution! 

I will have a look as soon as I can :)

**Comment by jakzal** [comment]
@pylebecq would you mind using curl instead of wget? It's already installed on both images. I wouldn't like to increase size of images for no reason.

**Comment by pylebecq** [comment]
@jakzal Thanks for your feedback. Indeed this is a very good idea. I made the necessary changes.

**Comment by jakzal** [comment]
@pylebecq have you considered alternatives (like https://github.com/krallin/tini)? I haven't used any of these in the past and just want to make sure we choose the right solution :)

**Comment by jakzal** [comment]
see https://bitbucket.org/atlassian/docker-atlassian-bitbucket-server/pull-requests/33/replace-dumb-init-with-tini-as-our-pid-1/diff

**Comment by jakzal** [comment]
I see. I'll research it a bit more and get back to you. Thanks!

**Comment by pylebecq** [comment]
From https://github.com/krallin/tini#using-tini, there is this paragraph:

> NOTE: If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run.

As I understand it, we can just use the image as they were before my changes, and simply add --init to the docker run command to get the same result.

I did not know that. I have to give it a shot and if it works maybe I can undo the changes and just add a mention of this in the readme instead.

**Comment by jakzal** [comment]
Indeed, updating the README with a suggestion to use `--init` sounds like a good plan!

**Comment by jakzal** [comment]
Thank you! :)

**Pull request merged**
