### PR TITLE
make simple-phpunit dir writeable

### LINKED ISSUE #110: Writeable simple-phpunit directory
Now that simple-phpunit is enabled, it could be nice to make its _default_ installation directory writeable.

That is: `/tools/.composer/vendor-bin/symfony/vendor/bin/.phpunit/`

It improves installing any version when running the container as a non-root user, without having to set `SYMFONY_PHPUNIT_DIR`.

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #110 

added `-R` to make the default installation writeable too.

### CODE REVIEW

**Comment by ro0NL** [comment]
it works, but produces:

```
Cannot create cache directory /tools/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
```

do you agree with this approach? if so i think composer cache should also be writeable.

**Comment by jakzal** [comment]
Shall we change the default user to non-root instead?

**Comment by jakzal** [comment]
Imo, if you're changing the user, you need to take care of setting permissions:

```
RUN adduser --no-create-home --disabled-password phpqa && chown -R phpqa /tools
USER phpqa
```

**Comment by dkarlovi** [comment]
I'm not convinced by this. If you need it, you probably want to mount Composer as a volume, in that case you don't care about the permissions in the image itself.

**Comment by ro0NL** [comment]
me neither, however for simple-phpunit being a phpunit version manager it might want to install new versions (#110). Currently this requires setting `SYMFONY_PHPUNIT_DIR` to something writeable, as such we'll also lose the default installation available in /tools.

what im currently doing

```
-w /app \
-v $(pwd):/app \
-e COMPOSER_HOME=/app/var/composer \
-e SYMFONY_PHPUNIT_DIR=/app/var/phpunit \
-e SYMFONY_PHPUNIT_VERSION=7.5
```

tend to keep it like this indeed. Effectively composer+phpunit are mounted and i only need to re-install e.g.  phpunit initially.

**Pull request closed without merging**
